version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: franquicias-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping').ok\" | grep 1"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: franquicias-app
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/reto_angela
    ports:
      - "8080:8080"

volumes:
  mongo_data:
