spring.application.name=franquicias-api
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/reto_angela}
logging.level.root=INFO
logging.level.com.vanegas.angela.franquicias_api=INFO
